### ISSUE TITLE
[1.16.5]Crash when I enter the world

### ISSUE THREAD

**Issue by DrSigma4164** [GizmoTheMoonPig/luggage#4]
When I enter the world I was crashed. Here is the crash log: https://bytebin.lucko.me/ozTynGyR6v

**Comment by DrSigma4164** [comment]
I also want to add that before leaving the world, I "upgraded" the chest by hitting it with lightning. I also updated the CC: Tweaked mod from version 1.100.6 to 1.100.8.
Perhaps some of the above is the cause of the crash.

**Comment by GizmoTheMoonPig** [comment]
the crash log points to the charged layer causing the crash. I don't understand why this would be happening, since I quite literally use the vanilla charged creeper layer for my stuff. I feel like something else might be at play here that the log isn't showing, some coremodding shenanigans or whatever. 
The best way to troubleshoot this would be to remove mods until you find the issue. I wish I could help more with this, but sometimes minecraft crash reports arent the most helpful. If you find the mod thats causing the issue, please let me know I can troubleshoot it myself from there!

**Comment by DrSigma4164** [comment]
Well, as soon as I notice this crash again, I'll write to you, I have already launched mineraft 4 times, this crash was not, maybe it was an isolated case.

**Comment by GizmoTheMoonPig** [comment]
gonna assume this was just a 1-off issue since I havent heard of this happening to anyone else. Let me know if this is still an issue, but im gonna close this for now. Thanks for reporting!
