### ISSUE TITLE
Possible incompat with Terrablender

### ISSUE THREAD

**Issue by Sunconure11** [GizmoTheMoonPig/luggage#8]
https://pastebin.com/PTbCiuUi

**Comment by itsdinkd** [comment]
its incompatible with Charm

**Comment by itsdinkd** [comment]
```Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_634::method_11112(Lnet/minecraft/class_2604;)V has incompatible changes at opcode 77 in callback charm.mixins.json:event.ClientSpawnEntityMixin->@Inject::hookOnEntitySpawn(Lnet/minecraft/class_2604;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_1299;)V from mod charm.```

**Comment by Sunconure11** [comment]
Issue still fires without Charm. Will get back with more info when I get my PC back later.

**Comment by Sunconure11** [comment]
https://github.com/wisp-forest/owo-lib/issues/40

This issue contains crash reports without Charm

**Comment by GizmoTheMoonPig** [comment]
There is no possible way this mod could be incompatible with a mod that does biome work. All it does is add a single mob that doesn't even naturally spawn. Hell, I would be surprised if it's incompatible with any mod at all. 
If you're gonna be reporting things like this to every mod mentioned in the crashlog, please try to isolate the issue first. Mods often get mentioned because something they do fails later on. Example, my packet stuff is mentioned, but there's no way that's what caused the initial crash, it's just a side effect. The packets couldn't register because the game crashed earlier. 
If you can make the crash happen with just luggage and terrablender installed, please reopen the issue. Otherwise, this crash wasn't caused by this mod.
